language: scala
sbt_args: -Djava.io.tmpdir=$TRAVIS_BUILD_DIR/tmp -Dpackaging.type=jar
script:
  - sbt +test
scala:
   - 2.12.8
jdk:
   - openjdk8
before_script:
  - mkdir $TRAVIS_BUILD_DIR/tmp
sudo: false
  
